name: template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http:
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  step_progress_indicator: ^1.0.2
  panara_dialogs: ^0.1.5
  get: ^4.7.2
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  toastification: ^3.0.2
  shared_preferences: ^2.5.3
  audioplayers: ^6.4.0
  flutter_dotenv: ^5.2.1
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  translator: ^1.0.3+1
  google_mobile_ads: ^6.0.0
  shimmer: ^3.0.0
  google_generative_ai: ^0.4.3
  firebase_core: ^3.14.0
  firebase_remote_config: ^5.4.5
  firebase_analytics: ^11.4.1
  firebase_crashlytics: ^4.3.1
  carousel_slider: ^5.1.1
  in_app_purchase: ^3.2.0
  onesignal_flutter: ^5.0.0
#  onesignal_flutter: ^5.3.0
  html: ^0.15.6
  app_tracking_transparency: ^2.0.6+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/gkquiz.db
    - assets/images/
    - assets/audios/
    - assets/
