import 'package:flutter/material.dart';
import 'package:template/core/theme/app_colors.dart';

final List<Color> gridColors = [
  kBlue,
  kTealGreen1,
  kDarkGreen2,
  kRed,
  kYellow,
  kCoral,
  kViolet,
  skyColor,
  kOrange,
];

final List<String> gridIcons = [
  'assets/disney.png',
  'assets/calendar.png',
  'assets/taj-mahal.png',
  'assets/prevention.png',
  'assets/quote.png',
  'assets/musical-note.png',
  'assets/chip.png',
  'assets/man.png',
  'assets/planting.png',
  'assets/pawprint.png',
  'assets/library.png',
  'assets/capitol.png',
  'assets/flask.png',
  'assets/computer.png',
  'assets/dollar-symbol.png',
  'assets/earth.png',
  'assets/atom.png',
  'assets/1st-place.png',
  'assets/fast-food.png',
  'assets/globe.png',
  'assets/sarcophagus.png',
  'assets/cowboy.png',
  'assets/colosseum.png',
  'assets/idea.png',
  'assets/elephant.png',
  'assets/dove.png',
  'assets/flag.png',
  'assets/lotus.png',
  'assets/office.png',
  'assets/pendulum.png',
  'assets/electricity.png',
  'assets/leaves-of-a-plant.png',
  'assets/experiments.png',
  'assets/soccer-player.png',
  'assets/economy.png',
  'assets/trophy.png',
  'assets/national-games.png',
];

final List<String> gridTexts = [
  'Disney',
  'Calendar',
  'Wonders of the world',
  'Disease prevention',
  'Famous quotes',
  'Music',
  'Electronics',
  'Human Body',
  'Agriculture',
  'Animals & Birds',
  'Books and Authors',
  'Capitals and Countries',
  'Chemistry',
  'Computer',
  'World Currencies',
  'Environment',
  'Everyday Science',
  'First in World',
  'Food and Drinks',
  'World Geography',
  'World History',
  'Historic Personalities',
  'Historical Places',
  'Inventions and Inventors',
  'National Animal',
  'National Bird',
  'National Anthem and Flag',
  'National Flower',
  'World Organization',
  'Physics',
  'Physical Education',
  'Plants',
  'General Science',
  'Sports',
  'World Economy',
  'Awards',
  'National Games',
];
